version: '3.8'

services:
  cache:
    container_name: cache
    image: redis:7.0.7-alpine
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --requirepass $NODE_UTIL_SCANNER_REDIS_PASSWORD

  scanner:
    container_name: scanner
    build:
      context: ..
      dockerfile: ./scanner/Docker/Dockerfile




