// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type EnrRecord struct {
	ID       string
	Fields   []string
	AddedAt  time.Time
	EditedAt time.Time
}

type Node struct {
	ID      string
	AddedAt time.Time
	SeenAt  time.Time
	Queries int32
	Ips     []string
}

type RlpRecord struct {
	ID              string
	RawName         string
	ProtocolVersion int32
	Caps            []string
	AddedAt         time.Time
	EditedAt        time.Time
}

type ScanRecord struct {
	ID        int64
	Node      string
	Ip        string
	Ports     []int32
	ScannedAt time.Time
	EditedAt  time.Time
}
