global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'crawler'
    static_configs:
      - targets: ['crawler:6061']
  
  - job_name: 'scanner'
    static_configs:
      - targets: ['scanner:6061']

